services:
  lab-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: lab-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test1234!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./lab-sqlserver/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./lab-sqlserver/entrypoint.sh:/entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Test1234!' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - lab-network
    entrypoint: ["/bin/bash", "/entrypoint.sh"]


  lab-php-nginx:
    build:
      context: ./lab-php-nginx
      dockerfile: Dockerfile
    container_name: lab-php-nginx
    ports:
      - "8001:8081"
      - "8002:8082"
    volumes:
      - ./laravel-apps/app-php81:/var/www/app-php81
      - ./laravel-apps/app-php84:/var/www/app-php84
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/php81-site.conf:/etc/nginx/sites-available/php81-site.conf
      - ./nginx-conf/php84-site.conf:/etc/nginx/sites-available/php84-site.conf
    depends_on:
      lab-sqlserver:
        condition: service_healthy
    networks:
      - lab-network

volumes:
  sqlserver-data:

networks:
  lab-network:
    driver: bridge
